const env = require("hardhat");
const path = require('path');
const PATH = '../image/';
const COMPAING_PATH = '../image-compaing/';

const testAccount = {
  displayName: "testAccount",
  company: "Peeranha",
  position: "TestInfo",
  location: "TestInfo",
  about: "TestInfo",
  avatar: "f"
};

const NFT = {
  name: "testAccount",
  description: "Peeranha",
  image: "",
  attributes: "TestInfo",
};

const testCommunity = {
  name: "testCommunity6.new",
  description: "testCommunity.new",
  website: "www.new",
  language: "ua.new",
};

const testTag = {
  title: "testTagNew",
  description: "testNewTag1",
};

const AchievementsType = { "Rating": 0, "Manually": 1 }

const achievements = (env) => {
  return [
    {
      maxCount: env === "prod" ? 10000 : 14,  
      lowerBound: env === "prod" ? 10 : 10, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Stranger.svg`),
      name: "I'm just having a look",
      description: "Limited edition NFT for achieving Stranger status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 8000 : 12,  
      lowerBound: env === "prod" ? 35 : 35, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}FoundingMember.svg`),
      name: "Working my way up",
      description: "Limited edition NFT for achieving 35 reputation on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 5000 : 10,  
      lowerBound: env === "prod" ? 100 : 10, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Newbie.svg`),
      name: "A beginning of a great journey",
      description: "Limited edition NFT for achieving Newbie status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 3000 : 5, 
      lowerBound: env === "prod" ? 500 : 50, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Junior.svg`),
      name: "Don't call me Junior!",
      description: "Limited edition NFT for achieving Junior status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 2000 : 4, 
      lowerBound: env === "prod" ? 1000 : 100, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Resident.svg`),
      name: "Peeranha is my home",
      description: "Limited edition NFT for achieving Resident status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 1000 : 3, 
      lowerBound: env === "prod" ? 2500 : 250, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Senior.svg`),
      name: "I can teach you anything",
      description: "Limited edition NFT for achieving Senior status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 500 : 2, 
      lowerBound: env === "prod" ? 5000 : 500, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}Hero.svg`),
      name: "This website needs a hero",
      description: "Limited edition NFT for achieving Hero status on Peeranha protocol among the first.",
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 1, 
      lowerBound: env === "prod" ? 10000 : 1000, 
      type: AchievementsType.Rating, 
      path: path.resolve(__dirname, `${PATH}suphero.svg`),
      name: "A living Legend",
      description: "Limited edition NFT for achieving Superhero status on Peeranha protocol among the first.",
      attributes: "",
    },
  ]
}

const manuallyAchievements = (env) => {
  return [
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}1.svg`),
      id: "1",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Koii Network community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://koii.peeranha.io/feed`,
      background_color: `A1F0DD`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}2.svg`),
      id: "2",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Koii Network community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://koii.peeranha.io/feed`,
      background_color: `FF70A6`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}3.svg`),
      id: "3",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Koii Network community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://koii.peeranha.io/feed`,
      background_color: `FEF8A4`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}4.svg`),
      id: "4",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Koii Network community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://koii.peeranha.io/feed`,
      background_color: `A1F0DD`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}5.svg`),
      id: "5",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Ankr community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://ankr.peeranha.io/feed`,
      background_color: `E2F8F7`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}6.svg`),
      id: "6",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Ankr community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://ankr.peeranha.io/feed`,
      background_color: `A1F0DD`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}7.svg`),
      id: "7",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Ankr community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://ankr.peeranha.io/feed`,
      background_color: `FFB7F9`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}8.svg`),
      id: "8",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Ankr community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://ankr.peeranha.io/feed`,
      background_color: `E2F8F7`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}9.svg`),
      id: "9",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Sui Global community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://suiglobal.peeranha.io/feed`,
      background_color: `FFB7F9`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}11.svg`),
      id: "10",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Sui Global community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://suiglobal.peeranha.io/feed`,
      background_color: `FFA59B`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}11.svg`),
      id: "11",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Sui Global community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://suiglobal.peeranha.io/feed`,
      background_color: `FFEEB0`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}12.svg`),
      id: "12",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Sui Global community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://suiglobal.peeranha.io/feed`,
      background_color: `FFB7F9`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}13.svg`),
      id: "13",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Functionland community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://functionland.peeranha.io/feed`,
      background_color: `FFA59B`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}14.svg`),
      id: "14",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Functionland community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://functionland.peeranha.io/feed`,
      background_color: `FFEEB0`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 7,
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}15.svg`),
      id: "15",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Functionland community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://functionland.peeranha.io/feed`,
      background_color: `A1F0DD`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}16.svg`),
      id: "16",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Functionland community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://functionland.peeranha.io/feed`,
      background_color: `FFA59B`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}17.svg`),
      id: "17",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Valist community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://valist.peeranha.io/feed`,
      background_color: `FF70A6`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}18.svg`),
      id: "18",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Valist community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://valist.peeranha.io/feed`,
      background_color: `FFA59B`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}19.svg`),
      id: "19",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Valist community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://valist.peeranha.io/feed`,
      background_color: `E2F8F7`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}20.svg`),
      id: "20",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Valist community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://valist.peeranha.io/feed`,
      background_color: `FF70A6`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}21.svg`),
      id: "21",
      name: "Grandmaster",
      description: `Unique NFT for making the most upvoted post in Orbis community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://orbis.peeranha.io/feed`,
      background_color: `FFEEB0`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}22.svg`),
      id: "22",
      name: "Mr. Smart",
      description: `Performance NFT for achieving the highest amount of reputation in Orbis community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://orbis.peeranha.io/feed`,
      background_color: `DDFFFD`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}23.svg`),
      id: "23",
      name: "Knowledge owner",
      description: `Advance NFT for achieving one of the highest ammount of reputation in Orbis community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://orbis.peeranha.io/feed`,
      background_color: `FFA59B`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}24.svg`),
      id: "24",
      name: "Gimme your Answers",
      description: `Knowledge-driven NFT for achieving 223 points of reputation in Orbis community on Peeranha during "Winter expertise contest 2023".`,
      external_url: `https://orbis.peeranha.io/feed`,
      background_color: `FFEEB0`,
      attributes: "",
    },
    {
      maxCount: env === "prod" ? 100 : 4,  
      lowerBound: 0, 
      type: AchievementsType.Manually, 
      path: path.resolve(__dirname, `${COMPAING_PATH}25.svg`),
      id: "25",
      name: "Best fren",
      description: `Unique NFT for being with Peeranha during "Winter expertise contest 2023".`,
      external_url: "https://peeranha.io/feed",
      background_color: `E2F8F7`,
      attributes: "",
    }
  ]
}

const mint_user_nft = () => {
  return [
    {
      id: 3,  
      adresses: ["0x30Cc2CA9115E8869F4D69B683Af49b3F7d96925b"]
    },
    {
      id: 4,  
      adresses: ["0x30Cc2CA9115E8869F4D69B683Af49b3F7d96925b"]
    }  
  ]
}

module.exports = { achievements, manuallyAchievements, mint_user_nft, NFT, testAccount, PATH, COMPAING_PATH, testCommunity, testTag };